chore: add PR check to verify examples
ExpediaGroup/rapid-java-sdk pull request #259
Opened 2024-12-17 08:46 UTC by anssari1

# Situation

Examples have no quality checks

# Task

Verify that updates to examples do not break compilation or linting rules

# Action

Add a GH action to verify examples whenever a PR updates them

# Testing

<img width="831" alt="Screenshot 2024-12-17 at 4 16 25 PM" src="https://github.com/user-attachments/assets/33f30099-95fb-4ac3-9a4f-98390ac4b4fe" />

# Results

Examples are verified as part of PR checks

# Notes

2024-12-17 13:31 UTC, mohnoor94 requested changes
The current checkstyle configuration is causing excessive line wrapping, particularly for logging statements and method calls, which reduces code readability. 

Suggestion: Let's increase the line length limit to 180 characters and potentially add exceptions for logging statements. This would maintain code cleanliness while avoiding unnecessary verbosity.

Thoughts?

2025-02-18 10:16 UTC, dtayeh submitted a review, later dismissed

2025-02-18 10:33 UTC, Mohammad-Dwairi submitted a review, later dismissed

2025-02-24 09:14 UTC, mohnoor94 approved these changes

2025-02-24 10:17 UTC, Mohammad-Dwairi approved these changes

2025-02-24 10:20 UTC, merged